name: CI-JS
on:
  push:
    paths-ignore:
      - 'scalus-secp256k1-jni/**'
      - '.github/workflows/**'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download uplc
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-uplc.yml
          name: uplc-linux-x86_64
          path: ./bin
      - name: Setup uplc
        run: |
          chmod +x ./bin/uplc
          echo "$PWD/bin" >> $GITHUB_PATH
      - uses: coursier/cache-action@v6
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
      - name: Build and test in Nix devshell
        run: nix develop .#ci --accept-flake-config --command bash -c "sbt ci-js"
      - name: Report test results
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "CI-JS ‚ùå - ${{ github.actor }} on ${{ github.ref_name }}"
          description: "[${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})"
          url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          username: "GitHub Actions"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          nodetail: true
          notimestamp: true